import { useCallback } from 'react';
import { useDataRefresh, DATA_SYNC_EVENTS } from '@/context/DataSyncContext';

export function useAutoRefresh(events, refetchCallback, deps = []) {
  useDataRefresh(
    Array.isArray(events) ? events : [events],
    useCallback(() => {
      if (refetchCallback) {
        refetchCallback();
      }
    }, [refetchCallback, ...deps])
  );
}

export const AUTO_REFRESH_EVENTS = {
  USERS: [DATA_SYNC_EVENTS.REFRESH_USERS, DATA_SYNC_EVENTS.USER_REGISTERED],
  SHELTERS: [DATA_SYNC_EVENTS.REFRESH_SHELTERS, DATA_SYNC_EVENTS.USER_REGISTERED],
  VETS: [DATA_SYNC_EVENTS.REFRESH_VETS, DATA_SYNC_EVENTS.USER_REGISTERED],
  PETS: [DATA_SYNC_EVENTS.REFRESH_PETS, DATA_SYNC_EVENTS.PET_CREATED, DATA_SYNC_EVENTS.PET_UPDATED, DATA_SYNC_EVENTS.PET_DELETED, DATA_SYNC_EVENTS.PET_STATUS_CHANGED],
  APPLICATIONS: [DATA_SYNC_EVENTS.REFRESH_APPLICATIONS, DATA_SYNC_EVENTS.ADOPTION_CREATED, DATA_SYNC_EVENTS.ADOPTION_UPDATED, DATA_SYNC_EVENTS.ADOPTION_APPROVED, DATA_SYNC_EVENTS.ADOPTION_REJECTED],
  COMPLAINTS: [DATA_SYNC_EVENTS.REFRESH_COMPLAINTS, DATA_SYNC_EVENTS.COMPLAINT_CREATED, DATA_SYNC_EVENTS.COMPLAINT_UPDATED, DATA_SYNC_EVENTS.COMPLAINT_RESOLVED],
  MEDICAL_RECORDS: [DATA_SYNC_EVENTS.MEDICAL_RECORD_UPDATED],
  VACCINATIONS: [DATA_SYNC_EVENTS.VACCINATION_UPDATED],
  ALL: [DATA_SYNC_EVENTS.REFRESH_ALL],
};
